### ISSUE TITLE
Accession missing Archive-It content

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-registrar-app#486]
Based on a conversation between @peterchanws @mjgiarlo and @edsu about the results of #438 we would like to fetch the missing WARC data and perform a one-time accessioning of the files as a set. Based on analysis this task involves:

1. Write a rake task or command line tool to audit that fetches specific WARC data from Archive-It, only from the collections listed below in a comment from Peter, using the audit results as input
2. Copy the resulting data to `was-registrar-app.stanford.edu:/was_unaccessioned_data/{item-dir-name}` 

Then Peter will do the following:

3. Kick off one-time registration using a new SDR collection for the whole set
4. Ensure that the job finishes and data is available in swap.stanford.edu 

If in the process of this it is easy to determine *why* the content wasn't downloaded the first time that would be a big bonus.

**Comment by peterchanws** [comment]
Here is the link to the list of collections 
https://docs.google.com/spreadsheets/d/1dPZBmuh6_NvjCTTCjI8PHfKpRRLXxPi0YxRDj-APhzQ/edit#gid=0

**Comment by justinlittman** [comment]
I think it will be even easier to just kick off the one-time registration as part of the rake task (so @peterchanws doesn't need to do it). Is that acceptable?

Also, @peterchanws is there a preferred format/structure for the source ids or is that something that you would like to specify for each one-time registration?

**Comment by justinlittman** [comment]
Am I correct in assuming that this should respect embargo?

**Comment by justinlittman** [comment]
I've re-audited the collections that failed the initial audit. https://docs.google.com/spreadsheets/d/1QRQMsuKp8PO19-oVRx9DbbO3FChUSZzSmr0wipQnNkw/edit#gid=0 has been updated with the results.

In addition, I have analyzed the reasons that WARCs might be missing. The following summarizes the results:

### Preceded fetch start month (10 collections)
Collections in WRA are configured with a month/year to begin fetching. These AIT collections contain WARCs that precede the fetch start date.

_Are there changes necessary to prevent this from happening?_

### Crawl spans month (3 collections) ###
The AIT crawl is configured to be performed at the end of the month; the WARC files are not stored until the next month. In these cases, the fetch happens after the crawl is performed but before the crawl is saved.

_To avoid this, fetching should be performed late in the month instead of daily._

### Crawl created in one month but saved in next month (2 collections)
I don't fully understand the AIT functionality, but for some manual crawls it seems that performing the crawl is a separate step from saving the crawl. In these cases, the fetch happens after the crawl is performed but before the crawl is saved.

_To avoid this, fetching should be performed late in the month instead of daily._

### Crawl item is in graveyard for unknown reasons (2 collections)
It is unclear what landed the item in the graveyard. These items do not include any WARCs.

### arc.gz are unsupported by WRA (1 collection)
_To address this, arc.gz support will need to be added in multiple code locations._

### Unexplained (2 collections)
I was unable to determine the reason that the WARCs were omitted.

### Single AIT collection is split between 2 SDR collections (1 collection)

**Comment by edsu** [comment]
It sounds like we may want to adjust the schedule to run fetches nearer the end of the month (the 28th) to avoid some of the issues you've identified here @justinlittman? Shall we create a separate issue for that?

**Comment by mjgiarlo** [comment]
@peterchanws says we can close this
