### ISSUE TITLE
Audit Archive-It collections that aren't in WRA

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-registrar-app#504]
Some older completed collections were created in Archive-It and never managed via WRA. Adjust the audit service so that these can be audited and potentially remediated.

**Comment by justinlittman** [comment]
Currently the audit rake task gets most of the parameters required to invoke an audit from a Collection AR object: https://github.com/sul-dlss/was-registrar-app/blob/main/lib/tasks/audit.rake#L7-L11

For this ticket, a version of the rake task should be created so that these parameters can be provided when invoking the rake task (so that a Collection AR object is not needed).
